.TH csnaketerm 6 "January 2021" "0.1.0"
.SH NAME
csnaketerm - The classic Snake game, right in your terminal
.SH SYNOPSIS
.B "csnaketerm "
[-h | --help | -v | --version]
.SH DESCRIPTION
The classic Snake game, right in your terminal. Play the game in an 80x24 terminal for an optimal experience, though larger terminal dimensions will also do.
.PP
Invoke without options to play the game.
.PP
.B -h, --help
.RS
Print the help message
.RE
.PP
.B -v, --version
.RS
Display the current version
.RE
.SH NOTES
This is a standalone program designed to be invoked directly, and as such, its behavior when standard input/output is redirected or piped to or from the program is unspecified.
.SH SEE ALSO
.I https://en.wikipedia.org/wiki/Snake_(video_game_genre)
